tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chat_test.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    transformer:
      model: transformer/generator
      model_file: models:blender/blender_90M/model
      override:
        model: transformer/generator
        no_cuda: True
      no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page
